spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:~/test;
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                show-sql: true
                format-sql: true
        hibernate:
            ddl-auto: create-drop # 테이블 생성하고 drop 해주는 옵션 -> 키고 끌때마다
mybatis:
    mapper-locations: classpath:mybatis/mapper/h2/**/**.xml
    type-handlers-package: com.springboot.springboot_work_out.mapper.typehandler
    type-aliases-package: com.springboot.springboot_work_out.model
    configuration:
        map-underscore-to-camel-case: true
        default-statement-timeout: 30
        default-fetch-size: 300