spring:
    datasource:
        url: jdbc:postgresql://localhost/postgres
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 1004
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                show-sql: true
                format-sql: true
        hibernate:
            ddl-auto: create-drop # 테이블 생성하고 drop 해주는 옵션 -> 키고 끌때마다