spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/testdb
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: 1004
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        properties:
            hibernate:
                show-sql: true
                format-sql: true
        hibernate:
            ddl-auto: create-drop # 테이블 생성하고 drop 해주는 옵션 -> 키고 끌때마다