spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:~/test;
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                show-sql: true
                format-sql: true
        hibernate:
            ddl-auto: create-drop # 테이블 생성하고 drop 해주는 옵션 -> 키고 끌때마다